{
  "openapi": "3.0.1",
  "info": {
    "version": "1.0.3",
    "title": "Swagger test",
    "description": "Showing off swagger-ui-express",
    "license": {
      "name": "MIT",
      "url": "https://opensourse.org/licenses/MIT"
    }
  },
  "consumes": ["application/json"],
  "produses": ["application/json"],
  "servers": [{ "url": "http://localhost:3000" }],
  "tags": [
    {
      "name": "Users",
      "description": "Signup endpoints"
    },
    {
      "name": "Users",
      "description": "Authentication endpoints"
    },
    {
      "name": "Users",
      "description": "Logout endpoints"
    },
    {
      "name": "Products",
      "description": "Calories and Products endpoinds"
    },
    {
      "name": "Products",
      "description": "Search query endpoints"
    }
  ],

  "paths": {
    "/api/users/signup": {
      "post": {
        "tags": ["Users"],
        "summary": "User registration",
        "parameters": [],
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "409": {
            "description": "Provided email already exist",
            "content": {}
          },
          "500": {
            "description": "Intarnal Server Error (invalid request body)",
            "content": {}
          }
        }
      }
    },

    "/api/users/login": {
      "post": {
        "tags": ["Users"],
        "summary": "User authentication",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Authentication's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AuthenticationRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuthenticationResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request (Login and Password fields are required)",
            "content": {}
          },
          "401": {
            "description": "Invalid creadentials (invalid request body)",
            "content": {}
          },
          "404": {
            "description": "This email was not found",
            "content": {}
          }
        }
      }
    },

    "/api/users/logout": {
      "post": {
        "tags": ["Users"],
        "summary": "User logout",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Logout's object",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LogoutRequest"
              }
            }
          }
        },
        "responses": {
          "204": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LogoutResponse"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {}
          }
        }
      }
    },

    "/api/products": {
      "get": {
        "tags": ["Products"],
        "summary": "Not recommended products",
        "parameters": [],
        "requestBody": {
          "description": "Blood type object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProductsRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProductsResponse"
              }
            }
          }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          }
        }
      }
    },

    "/api/products/foods?name=query": {
      "get": {
        "tags": ["Products"],
        "summary": "Search by query",
        "parameters": [
          {
          "in": "query",
          "name": "name",
          "type": "string",
          "description": "Name of product "
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SearchProductsResponse"
              }
            }
          }
          },
          "204": {
            "description": "Successful operation. No content",
            "products": {}
          }
        }
      }
    }
  },

  "components": {
    "schemas": {
      "RegistrationRequest": {
        "type": "object",
        "required": ["name", "login", "password"],
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Roman"
          },
          "login": {
            "type": "string",
            "description": "User's login",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          }
        }
      },
      "RegistrationResponse": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Roman"
          },
           "login": {
            "type": "string",
            "description": "User's login",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "hashed password"
          }
        },
        "example": {
          "status": "Success",
          "code": 201,
          "message": "User with name: 'Roman' added successfully!",
          "data": {
            "id": "60a68ec360b8d40858e3f15b",
            "name": "Roman",
            "login": "user@gmail.com",
            "password": "$2a$06$qANrU55.gBBgLwMroVVGC.2C9J0IjOGnISKB12KNTeonCJDtYhH9W"
          }
        }
      },

      "AuthenticationRequest": {
        "type": "object",
        "required": ["login", "password"],
        "properties": {
          "login": {
            "type": "string",
            "description": "User's login",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          }
        }
      },
      "AuthenticationResponse": {
        "type": "object",
        "properties": {
          "login": {
            "type": "string",
            "description": "User's login",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "hashed password"
          }
        },
        "example": {
          "status": "Success",
          "code": 200,
          "message": "User with login: 'user@gmail.com' logged in!",
          "data": {
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYTY4ZWMzNjBiOGQ0MDg1OGUzZjE1YiIsImlhdCI6MTYyMTUyODM5OSwiZXhwIjoxNjIxNjE0Nzk5fQ.4nfCGSY1JsB1NX-N4P_lpZQ6AzaDOLITflE6lbEyNrM"
          }
        }
      },

      "LogoutRequest": {
        "type": "object",
        "description": "No content",
        "example": "No content"
      },
      "LogoutResponse": {
        "type": "object",
        "description": "No content",
        "example": "No content"
      },

      "ProductsRequest": {
        "type": "object",
        "required": ["groupBloodNotAllowed"],
        "properties": {
          "groupBloodNotAllowed": {
            "type": "object",
            "description": "Blood type",
            "example": [null, false, false, false, true]
          }
        }
      },
      "ProductsResponse": {
        "type": "object",
        "items": {
          "properties": {
            "title": {
              "type": "string",
              "description": "Not recommended products",
              "example": {"ru": "Арахис сушеный", "ua": "Арахіс сушений"}
            }
          }
        },
        "example": {
          "status": "Success",
          "code": 200,
          "message": "Not recommended products",
          "products": [
            {
              "_id": "5d51694902b2373622ff5c4d",
              "title": {
                "ru": "Масло арахисовое PB2 сухое обезжиренное",
                "ua": "Олія арахісове PB2 сухе знежирене"
              }
            }
          ]
        }
      }
    },


    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}